### ISSUE TITLE
How to show "item  slug" in my view?

### ISSUE THREAD

**Issue by JoseCage** [spatie/laravel-sluggable#10]
Hello.. I need help.
 How to correctly configure the sluggable in my routes, controller to show the item when user get "sitename/item/item-name" (item-name is the slug in this case)

In my tests i tried the code above in my controller. So, it isn't work..
<code>
public function show(Request $slug){
      $product Product::whereSlug($slug)->firstOrFail();
    	return view('product.product')->with('product', $product);
    }
</code>

**Comment by sebastiandedeyne** [comment]
If you typehint `Request`, Laravel is gonna inject a `Request` object, which isn't what you want here.

Assuming the route looks something like `sitename/item/{slug}`, this should work:

```
public function show($slug)
{
    $product Product::whereSlug($slug)->firstOrFail();

    return view('product.product')->with('product', $product);
}
```

Alternatively, if you also need the request object injected:

```
public function show(Request, $request, $slug)
{
    $product Product::whereSlug($slug)->firstOrFail();

    return view('product.product')->with('product', $product);
}
```

More on controller method injection: https://laravel.com/docs/5.2/controllers#dependency-injection-and-controllers

**Comment by JoseCage** [comment]
Thank You so much @sebastiandedeyne now it's working for me... Awesome..

Please continue with development of this module.,  :+1:
