### ISSUE TITLE
Return slug as string

### ISSUE THREAD

**Issue by caiokawasaki** [spatie/laravel-sluggable#101]
Instead of save the slug into the database should exist the option to return the slug as string...

Something like: 

```
$slug = SlugOptions::create()
            ->generateSlugsFrom('name')
            ->toString();
```

I already have a logic in my code and I can not allow the package to save to the database before executing my logic...

**Comment by lukadriel7** [comment]
Hello, You may want to use Str::Slug(). It will let you get a slug without saving to the database.
https://laravel.com/docs/5.8/helpers#method-str-slug

**Comment by caiokawasaki** [comment]
@lukadriel7 but I want to use the ability of this package to add unique integers to the slug...

**Comment by lukadriel7** [comment]
Which ability are you speaking of ? How do you add those unique integers ?

**Comment by AlexVanderbist** [comment]
@lukadriel7 it's enabled by default. When a generated slug already exists we'll make sure that the new slug is uniqe:
https://github.com/spatie/laravel-sluggable/blob/master/src/HasSlug.php#L105-L115

@caiokawasaki this package wasn't intended to generate unique slugs without saving them to the database. However, if you really wanted to, you could re-use some code from the `HasSlug` trait to do so: 
```php
// in your model:
 $slug = $this->makeSlugUnique($this->generateNonUniqueSlug());
```
