### ISSUE TITLE
doNotGenerateSlugsOnUpdate still allows duplicate slugs

### ISSUE THREAD

**Issue by JoshuaDoshua** [spatie/laravel-sluggable#102]
With `doNotGenerateSlugsOnUpdate` (and not allowing duplicate slugs by default) a manual update of a slug can be duplicate or non-unique.

This could be solved with declaring unique column in the database, but it changes the user experience when the rest are auto-generated/auto-incremented.

Something like an `alwaysForceUniqueSlug()` method?

It seems like it may be difficult and conflicting to try to manually handle this with a custom observer. Any guidance/pointers with this case would be appreciated.

**Comment by AlexVanderbist** [comment]
I think you should be alright implementing this using a custom updating hook. There wont be any conflicts if `generateSlugsOnUpdate` is turned off. Maybe something like this?

```php
    protected static function boot()
    {
        static::updating(function (Model $model) {
            // when updating the model, always make the given slug unique
            $this->$slugField = $this->makeSlugUnique($this->$slugField);
        });
    }
```

I'm gonna close this issue for now due its age but feel free to open another issue if you're still having issues with this :)

**Comment by JoshuaDoshua** [comment]
@AlexVanderbist Thanks, not having issues with it, but I opened as a general feature request / topic of discussion.
Objectively, if laravel-sluggable has an option to prevent duplicate slugs, it should also prevent duplicate slugs on update IMO.
