### ISSUE TITLE
Increment value starts with 2

### ISSUE THREAD

**Issue by zarulizham** [spatie/laravel-sluggable#103]
Hello,

Is it possible to start increment value for duplicate slug starting with 2? For example:

| ID        | Title           | Slug  |
| ------------- |-------------| -----|
| 10001      | example title  | example-title |
| 10002      | example title  | example-title-2 |
| 10003      | new title  | new-title |
| 10004      | example title  | example-title-3 |

For an example, maybe we can extends with `->incrementStartsWith(2);`

**Comment by freekmurze** [comment]
On your sluggable class add a `makeSlugUnique` function and implement your own logic there. This is what the package does by default: https://github.com/spatie/laravel-sluggable/blob/1467323aaee9b09e1b09d5b55dfab723be06f931/src/HasSlug.php#L105-L115

**Comment by zarulizham** [comment]
Got it. Thank you!
