### ISSUE TITLE
This package does not work when using a ModelObserver

### ISSUE THREAD

**Issue by francoislevesque** [spatie/laravel-sluggable#105]
I created a UserObserver and registered it in AppServiceProvider and the slugs are not created automatically anymore.

`SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value`

**Comment by atymic** [comment]
I've tested this on a fresh laravel install and it seems to be working correctly:

```
>>> $m = \App\Post::create(['name' => 'test324234', 'content' => 'sddsa'])
/home/evan/code/oss/spatie/test-installs/validation-test/app/Observers/PostObserver.php:17:
string(7) "created observer method executed"
=> App\Post {#3188
     name: "test324234",
     content: "sddsa",
     slug: "test324234-2",
     updated_at: "2019-06-04 22:50:38",
     created_at: "2019-06-04 22:50:38",
     id: 4,
   }
>>> 
```

**Comment by najathi** [comment]
When I used the insert, got an error
**_PDOException::("SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value"_**

**Use create(), don't use the insert().** 

` \App\Model\Category::create($category);`
