### ISSUE TITLE
Slugs are not created for UTF-8 Characters.

### ISSUE THREAD

**Issue by samgan-khan** [spatie/laravel-sluggable#106]
I have a website which supports title in HINDI. I am using the plugin but instead of slug m getting an empty string but as the unique slugs are created it returns as only "-number" e.g "-1", "-2". 

It would be a great help if you can look into this matter.

I am attaching the screenshot for more clarification.

![Screenshot (31)](https://user-images.githubusercontent.com/29948727/58453532-90d60500-812c-11e9-8805-3768977aea06.png)

**Comment by atymic** [comment]
Can you post the code you are using on your model? Are you setting the language correctly?

```php
public function getSlugOptions() : SlugOptions
{
    return SlugOptions::create()
        ->generateSlugsFrom('name')
        ->saveSlugsTo('slug')
        ->usingLanguage('hi'); // Set the language to Hindi
}
```

**Comment by samgan-khan** [comment]
my site uses a combination of Hindi and English titles to give a particular language won't help. but still for the sake of testing I did it. and this was also not working. 

laravel Str helper is making is null, 
`Str::slug($this->getSlugSourceString(), $this->slugOptions->slugSeparator, $this->slugOptions->slugLanguage);`

this line in generateNonUniqueSlug() is makin the string null.

**Comment by atymic** [comment]
My suggestion would be to try overriding the `generateNonUniqueSlug` method on your model to use an alternate slugging library that better supports languages.

Library: https://github.com/cocur/slugify

Then replace the method with:
```php
protected function generateNonUniqueSlug(): string
{
    $slugField = $this->slugOptions->slugField;
    if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
        return $this->$slugField;
    }
    
    $slugify = new \Cocur\Slugify(['rulesets' => ['default', 'turkish']]);

    return $slugify->slugify($this->getSlugSourceString(), $this->slugOptions->slugSeparator);
}
```

**Comment by atymic** [comment]
Potentially in the future support for different slugging methods could be implemented.

**Comment by samgan-khan** [comment]
I did the same for now, but this plugin is quite nice in other areas. so thought on shining some light over the issue. I think ill provide a PR to fix the same. Let's see what happens.
@atymic anyway thanks for the time.

**Comment by atymic** [comment]
No worries :smile:

**Comment by AlexVanderbist** [comment]
I agree with @atymic on overriding the `generateNonUniqueSlug` method. Alternatively you can try to get a fix merged into Laravel itself 👍
