### ISSUE TITLE
Return value of App\Profile::getSlugOptions() must be an instance of App\SlugOptpions, instance of Spatie\Sluggable\SlugOptions returned

### ISSUE THREAD

**Issue by Icrmsoftware** [spatie/laravel-sluggable#108]
Facing this error, please help

![image](https://user-images.githubusercontent.com/34971088/62863119-88519b80-bd25-11e9-81c8-e79e51dda1b5.png)

**Comment by davejamesmiller** [comment]
Simple typo:
![image](https://user-images.githubusercontent.com/236616/62981288-c1226b00-be20-11e9-894f-28fd375cfab0.png)

**Comment by riasvdv** [comment]
Thanks @davejamesmiller
