### ISSUE TITLE
Allow the use of Laravel 6.0

### ISSUE THREAD

**Issue by belzaaron** [spatie/laravel-sluggable#113]
Hey, great package! Since the release date of Laravel 6.0 is September 3rd 2019, I think it'd be beneficial for the community to update the package version constraints to allow the use of 6.0.

Since this release is not actually a major release but, a bump to use SemVer there should be no changes to the codebase (as far as I am aware).

Thanks and I'll work on a PR and link it here.
https://github.com/spatie/laravel-sluggable/pull/114

**Comment by rubenvanassche** [comment]
Release tagged!
