### ISSUE TITLE
Updating Slug when title did not update.

### ISSUE THREAD

**Issue by kingeke** [spatie/laravel-sluggable#118]
Ok so this is weird, but lets assume we have three posts with the same title,  like this table

```
title   |   slug
--------------------------------------------------------------
Title   |  title
Title   |  title-1
Title   |  title-2
```

so then let's say we delete the post with slug (title-1) the table becomes
```
title   |   slug
--------------------------------------------------------------
Title   |  title
Title   |  title-2
```

then if we update the post with slug (title-2) without changing the title (lets assume the table has more data than that *winks*), the slug updates and becomes title-1
```
title   |   slug
--------------------------------------------------------------
Title   |  title
Title   |  title-1
```

why ???, because now that I updated my post I want to re-fetch it using the slug used in updating and it returns null. how can i fix this ?

**Comment by kingeke** [comment]
also if using 

```php
doNotGenerateSlugsOnUpdate();
```
method, it does not regenerate on update, good. Then assuming I update the title, and add this function in my code on update
```php
if($post->title != $request['title'] {
   $post->generateSlug();
   $post->save();
}
```

it does not update it after it runs, it updates it after the second update, so assuming I update the title to "First Post" the slug still remains "title" then if I update the title the third time to "Second Post" the slug becomes "first-post", like it's slow to update or something

**Comment by axelitus** [comment]
This behavior is by design to prevent replacing slugs that have been generated manually. What you need to do is empty your slug field so that it can be automatically generated, so your code needs to be:

```php
if ($post->title != $request['title']) {
    $post->slug = '';
    $post->generateSlug();
    $post->save();
}

The other behavior (updating from title-2 to title-1) seems weird to me, it should not happen because of the same reason. Because the slugs are usually used for identifying objects with URLs or the like, a change to the slug when it is already created should not be the default. Only in the case you purposedly set the slug to nothing should it be re-generated.
```
