### ISSUE TITLE
Proposal: add explicit model binding

### ISSUE THREAD

**Issue by justijndepover** [spatie/laravel-sluggable#121]
I know there were multiple other PR's that allowed model binding on the slug field by overriding the `getRouteKeyName` function. But that breaks the binding with `id`s

I think it would be better to leave the normal binding as is and just create a new one like so:

```php
Route::get('products/{product}', function (App\Product $product) {
    // here the binding was made with the product id
});

Route::get('products/{product_slug}', function (App\Product $product) {
    // here the binding was made with the product slug
});
```

Not sure how to achieve this. I currently added a `SlugServiceProvider` where I bind all slug enabled models but this could be automated I guess?
```php
public function boot()
{
    Route::bind('product_slug', function ($value) {
        return \App\Product::where('slug', $value)->first() ?? abort(404);
    });
}
```

thoughts?

**Comment by bram1028** [comment]
What about supporting both id and slug with the same implicit binding? Use this on the model class:

```php
    /**
     * Retrieve the model for a bound value.
     *
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function resolveRouteBinding($value)
    {
        if (is_numeric($value)) {
            return $this->findOrFail((int) $value);
        } else {
            return $this->where($this->getSlugOptions()->slugField, $value)->firstOrFail();
        }
    }
```

You can put this in another trait or base class and add additional logic to check if it uses `HasSlug`.

**Comment by justijndepover** [comment]
I'm happy with that
