### ISSUE TITLE
Slug Arabic problem

### ISSUE THREAD

**Issue by AO-IO** [spatie/laravel-sluggable#124]
when creating a slug from a name .  the slug is in English letters
example :

name = مقالة جديدة
slug = mk-l-gdyd

it should be: مقالة-جديدة

Any idea how to solve this issue?

**Comment by Khalid3bdallah** [comment]
The same happened with me.
Any updates about this issue?

**Comment by LaithSJ** [comment]
Has anyone faced this issue and solved it ? Why this ticket closed ? i am having this issue .

**Comment by samerzaki** [comment]
I have the same problem

**Comment by AO-IO** [comment]
> I have the same problem

 this may help 

use this package https://github.com/cocur/slugify.

go to HasSlug Trait in `endor/spatie/laravel-sluggable`

at the top use use `Cocur\Slugify\Slugify;`

override the method `generateNonUniqueSlug()`
```PHP
   protected function generateNonUniqueSlug(): string
    {
        $slugField = $this->slugOptions->slugField;
        if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
            return $this->$slugField;
        }

        $slugify = new Slugify(['rulesets' => ['default', 'arabic']]);

        return $slugify->slugify($this->getSlugSourceString(), $this->slugOptions->slugSeparator);
    }
```

**Comment by AO-IO** [comment]
> I have the same problem

I remember is solved this issue by the following : 

using https://github.com/cocur/slugify.

go to HasSlug Trait in `vendor/spatie/laravel-sluggable`

at the top use use `Cocur\Slugify\Slugify;`

override the method `generateNonUniqueSlug()`

```PHP
protected function generateNonUniqueSlug(): string
    {
        $slugField = $this->slugOptions->slugField;
        if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
            return $this->$slugField;
        }

        $slugify = new Slugify(['rulesets' => ['default', 'arabic']]); // your language 

        return $slugify->slugify($this->getSlugSourceString(), $this->slugOptions->slugSeparator);
    }
```

**Comment by AO-IO** [comment]
> I have the same problem

I remember solving this issue by the following : 

using https://github.com/cocur/slugify.

go to HasSlug Trait in `vendor/spatie/laravel-sluggable`

at the top use use `Cocur\Slugify\Slugify;`

override the method `generateNonUniqueSlug()`

```PHP
protected function generateNonUniqueSlug(): string
    {
        $slugField = $this->slugOptions->slugField;
        if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
            return $this->$slugField;
        }

        $slugify = new Slugify(['rulesets' => ['default', 'arabic']]); // your language 

        return $slugify->slugify($this->getSlugSourceString(), $this->slugOptions->slugSeparator);
    }
```

**Comment by salmazz** [comment]
anyone found solution for this problem ?

**Comment by AO-IO** [comment]
I ended up using this package [eloquent-sluggable](https://github.com/cviebrock/eloquent-sluggable) . after installing follow this [Slugify-Arabic-fix](https://github.com/AO-IO/Slugify-Arabic-/).

**Comment by AO-IO** [comment]
> anyone found solution for this problem ?

I ended up using this package [eloquent-sluggable](https://github.com/cviebrock/eloquent-sluggable) . after installing follow this [Slugify-Arabic-fix](https://github.com/AO-IO/Slugify-Arabic-/).

**Comment by samerzaki** [comment]
just override the method **generateNonUniqueSlug()** used for generating slugs to allow slugify arabic letters
in your model, write:
```
protected function generateNonUniqueSlug(): string
{
    $slugField = $this->slugOptions->slugField;

    if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
        return $this->$slugField;
    }

    $txt = strtolower( trim( $this->getSlugSourceString() ) );
    $txt = preg_replace('|[^a-z-A-Z\p{Arabic}0-9 _]|iu', '', $txt);
    $txt = preg_replace('/\s+/', ' ', $txt);
    return str_replace(' ', $this->slugOptions->slugSeparator, $txt);
}
```

**Comment by salmazz** [comment]
@samerzaki i am added your function in my modal 
what about this function   

```
 /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::createWithLocales(['en', 'ar'])
            ->generateSlugsFrom(function($model, $locale) {
                return "{$model->name}";
            })
            ->saveSlugsTo('slug')
            ->usingLanguage('ar');
    } 

```
?

**Comment by salmazz** [comment]
@samerzaki  i get this result when making override 
i need in two lang get the slug `{
  "name": {
    "ar": "سلمي",
    "en": "salma"
  },
  "slug": {
    "en": "salma",
    "ar": "-2"
  },`
