### ISSUE TITLE
Breaking change in minor update

### ISSUE THREAD

**Issue by jandreasn** [spatie/laravel-sluggable#134]
I believe the PHP 7.4 requirement in version 2.3.0 is a breaking change and should have been tagged as 3.0.0 according to semver. This just broke our build after a composer update and could break a lot of others' too.

**Comment by freekmurze** [comment]
I don't think it is a breaking change. Composer shouldn't allow you to install packages whose minimum requirements are not met.

**Comment by jandreasn** [comment]
That is correct and Composer normally doesn't. But in this shift to PHP 7.4 I run 7.4 locally to to test and prepare our code base for the 7.4 production upgrade. Ideally I should have specified targeted php version in composer.json and that would solve this issue, but that's easy to forget. 

I still think your change is more than a minor update though and you should not rely on Composer to safe guard against conflicts. Semver is not Composer. Semver documents and communicates changes by itself and a major version bump in this case would be more clear. But maybe this is just my opinion. I hope you will give it some thought at least.

**Comment by freekmurze** [comment]
I've discussed this with others in the pas. According to semver it is allowed to change the dependencies of a library as long as your own public API does not change.  If you still think a semver rule is broken, please point me the rule you think is broken at https://semver.org/

I think it's good practice to use composers `platform` config option by default everywhere, so this type of problem is prevented.
