### ISSUE TITLE
Syntax error: unexpected 'SlugOptions'

### ISSUE THREAD

**Issue by kampit** [spatie/laravel-sluggable#136]
syntax error, unexpected 'SlugOptions' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

https://github.com/spatie/laravel-sluggable/blob/master/src/HasSlug.php#L11

**Comment by freekmurze** [comment]
The tests prove that the code doesn't have syntax errors. Make sure you are running the required version of PHP.

**Comment by Hansum** [comment]
@freekmurze Hi, sorry for this dumb question but what is the required php version right now for laravel-sluggable?

**Comment by freekmurze** [comment]
Take a look in composer.json
