### ISSUE TITLE
The tests prove that the code doesn't have syntax errors. Make sure you are running the required version of PHP.

### ISSUE THREAD

**Issue by rushxs7** [spatie/laravel-sluggable#139]
The tests prove that the code doesn't have syntax errors. Make sure you are running the required version of PHP.

_Originally posted by @freekmurze in https://github.com/spatie/laravel-sluggable/issues/136#issuecomment-570719828_

I have tested this on php7.4. sluggable version 2.3.
I temporarily fixed the issue by reverting to version 2.2.1 but i wanted some features of version 2.3.

Is there any way to fix this? Should i have any php modules installed?

**Comment by freekmurze** [comment]
All I can say is that our tests seem to run fine, and we don't see any problems on our end.

https://github.com/spatie/laravel-sluggable/commit/c42faad176998190f78820e484b779b9a85fa6ec/checks?check_suite_id=345417697

See what the output is of `phpinfo()` in the environment where you run our package. Be aware that the CLI and web request could be handled by different PHP versions.
