### ISSUE TITLE
Laravel 6 & PHP 7.4 Incompatability

### ISSUE THREAD

**Issue by ThatGuyMelo** [spatie/laravel-sluggable#140]
My enviroment:

PHP version: 7.4.1 (and yes - i checked the cli version)
Laravel version: 6.2

When creating slugs, fatal error throws:

Symfony\Component\Debug\Exception\FatalThrowableError
syntax error, unexpected 'SlugOptions' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 

The problem seems to be line 11 on vendor/spatie/laravel-sluggable/src/HasSlug.php:11

Please advise further...

**Comment by freekmurze** [comment]
Pretty sure this is caused by a wrong PHP version being used. Make sure all web requests are handled by the right PHP version too

**Comment by mydnic** [comment]
@freekmurze I just upgraded le PHP version from the forge UI and got this error as well... does that mean Forge installed an incorrect PHP7.4 version ?

**Comment by freekmurze** [comment]
I guess there is something wrong then. Our testsuite runs perfectly under Laravel 6 / PHP 7.4

https://github.com/spatie/laravel-sluggable/commit/c42faad176998190f78820e484b779b9a85fa6ec/checks?check_suite_id=345417697

If you think the package is in error, please submit a failing test for me to fix.

**Comment by szgalbraith** [comment]
I just had a similar problem. I'm currently running everything locally with the correct versions. Serving the site through artisan works fine and no error, but if I run it using Valet I get the error.
