### ISSUE TITLE
Reserved slug words

### ISSUE THREAD

**Issue by JonathanPort** [spatie/laravel-sluggable#143]
Hi Guys, love the package. I'm making a Wordpress style Page / Post system. I'm using this package to generate slugs but I need a way to pass an array of reserved slugs for core system routes that aren't dynamically made such as `/profile` for example. If the slug matches this, then append a number such as `profile-1`. 

I tried to apply the logic in the getSlugOptions() method but looking through the source, I'd need to override the `HasSlug::addSlug` method and add in a new method, something like `makeSlugUniqueFromReservedWords`. I can handle this not a problem but would be a really cool feature to add!

Wondering your thoughts and happy to do a PR?

**Comment by freekmurze** [comment]
Feel free to submit a PR with test and an updated readme.Thanks!
