### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-sluggable#146]
Can this package laravel 7?

current error:

```
  Problem 1
    - spatie/laravel-sluggable 2.4.0 requires php ^7.4 -> your PHP version (7.2.19) does not satisfy that requirement.
    - spatie/laravel-sluggable 2.3.0 requires php ^7.4 -> your PHP version (7.2.19) does not satisfy that requirement.
    - Conclusion: remove laravel/framework v7.0.7
    - Conclusion: don't install laravel/framework v7.0.7
```

**Comment by freekmurze** [comment]
Only on PHP 7.4

**Comment by robertnicjoo** [comment]
@freekmurze Please allow me to respond before you close the issue,

I do have `php 7.4` installed

![Untitled](https://user-images.githubusercontent.com/8672823/76174701-82e50280-61db-11ea-9ceb-3f6e9361d003.png)

**To those that come here with same issue:**

If you just download and set `7.4` you need to restart your system (restarting your virtual host alone is not enough)


Thanks
