### ISSUE TITLE
Adapt minimum requirements of Laravel

### ISSUE THREAD

**Issue by patriziotomato** [spatie/laravel-sluggable#148]
Hi,

this is to be closed, but let my recommend, if you a building Laravel packages, to comply to Laravels minimum requirements. Else people will have the problem to upgrade to newest Laravel version (and comply to PHP 7.2.10 for example) because you dropped support for this.

Yes, I perfectly see the reason and motivation for you, but please spend some seconds to people like us, being not able to upgrade to Laravel 7 without removing/replacing your Library because our servers still are running on PHP 7.2. Yes the time for this is limited, but I hope you get the point.

So the wish from outside in would be for you to support same software versions as your depending framework do ;-)

**Comment by freekmurze** [comment]
Thanks for your comment. We'll consider this.
