### ISSUE TITLE
Does translatable support version 2.2.2

### ISSUE THREAD

**Issue by weeradach** [spatie/laravel-sluggable#156]
Because my app use laravel version 6 therefore require version 2.2.2

**Comment by kukukk** [comment]
It seems that the package is not using any Laravel 6 specific code, but it requires PHP 7.4. If you plan to use it on PHP 7.4 you can simply modify the composer.json and it will work. If you plan to use it on older version of PHP, I made a fork and replaced the PHP 7.4 specific code, so it works with Laravel 6 on PHP 7.3
It is available here: https://github.com/kukukk/laravel-sluggable
