### ISSUE TITLE
Trait 'Spatie\Sluggable\HasTranslatableSlug' not found

### ISSUE THREAD

**Issue by KunwarSagar** [spatie/laravel-sluggable#157]
```
Symfony\Component\ErrorHandler\Error\FatalError
Trait 'Spatie\Sluggable\HasTranslatableSlug' not found

```
I installed both package laravel-sluggable and laravel-translatable. But HasTranslatableSlug is nowhere to be found. What am I doing wrong? Should I copy code directly?

**Comment by riasvdv** [comment]
Which version of the package are you on? The HasTranslatableSlug trait was added in 2.5.0

**Comment by freekmurze** [comment]
Closing as it probably isn't an issue with the code of the package.

**Comment by KunwarSagar** [comment]
I didn't choose any version as such. I followed read me as it is. I believe composer installs the latest version. Anyway it didn't help in anyway so i had to do it manually. I wanted to create slugs in Japanese.
