### ISSUE TITLE
Add the option to disable withoutGlobalScopes()

### ISSUE THREAD

**Issue by john-ibsa** [spatie/laravel-sluggable#159]
**Problem**

We currently use a multi-tenancy setup with a single database. This uses a Global Scope of `BelongsToTenant` to ensure queries only operate on current tenant records. 

This means that when a slug is created, `withoutGlobalScopes()` prevents slugs being scoped to a single tenant. 

**Proposed Solution**

Add a `slugOption` to disable `withoutGlobalScopes()`

Would be great if this could be updated. 

This package works so well for us.

**Comment by freekmurze** [comment]
Feel free to submit a PR for this with tests and an updated readme.
