### ISSUE TITLE
Tests failing because of "recent" change

### ISSUE THREAD

**Issue by axelitus** [spatie/laravel-sluggable#163]
The tests are failing because there was some "recent" change introduced in `Illuminate\Support\Str::slug` method.
![image](https://user-images.githubusercontent.com/732441/92297215-8b0bc980-ef02-11ea-88a2-869075f6c79c.png)

Running `Str::slug('a€')` now returns `aeur` instead of `a-euro` like it used to.

When running the tests with the `--prefer-lowest` flag it works as documented by the test.

The failing test is [it_can_handle_weird_characters_when_generating_the_slug](https://github.com/spatie/laravel-sluggable/blob/5b0c995ad7c108e160d3b11382dc53eebb7d6159/tests/HasSlugTest.php#L152) and it is because the value set in [line 165](https://github.com/spatie/laravel-sluggable/blob/5b0c995ad7c108e160d3b11382dc53eebb7d6159/tests/HasSlugTest.php#L165).

**Comment by axelitus** [comment]
The error is because on February 7 the `Str::slug` method was changed to use https://github.com/voku/portable-ascii library:
https://github.com/laravel/framework/commit/eea5d5df51ddc2055e71436913deeed97ccaaaa2

This change was reverted on March 5:
https://github.com/laravel/framework/commit/e4f22d855b429e4141885d542438c859f84bfe49

![image](https://user-images.githubusercontent.com/732441/92306486-fed6c200-ef54-11ea-9f60-9fba235a3069.png)

**Comment by freekmurze** [comment]
Thanks, I'll take a look at the PR.
