### ISSUE TITLE
Unable to install in laravel 8.

### ISSUE THREAD

**Issue by shankhadevpadam** [spatie/laravel-sluggable#169]
This package doesn't install in laravel 8. But another spatie package is installed.

```
Problem 1
    - Installation request for spatie/laravel-sluggable ^2.5 -> satisfiable by spatie/laravel-sluggable[2.5.0].
```

**Comment by bjuppa** [comment]
Laravel 8 support seems to be on its way, this PR was merged https://github.com/spatie/laravel-sluggable/pull/168 but the tests seems to fail now so we'll probably just wait a little for the new release!

**Comment by bjuppa** [comment]
[`2.5.1`](https://github.com/spatie/laravel-sluggable/releases/tag/2.5.1) of this package was released yesterday, that will make it installable with Laravel 8, and hopefully solve your issue @shankhadevpadam!

**Comment by shankhadevpadam** [comment]
Thanks.
