### ISSUE TITLE
Implicit route model binding won't work with laravel-translatable integration

### ISSUE THREAD

**Issue by andriihorpenko** [spatie/laravel-sluggable#171]
Whenever I visit the resourceful controller URL with getRouteKeyName() set to `slug` on the model, I get 404. I don't see tests with controller, maybe that's why this issue is not covered. Project setup: Laravel 8, laravel-sluggable and laravel-translatable packages installed.

**Model:**
```php
class Restaurant extends Model
{
    use HasFactory, HasTranslations, HasTranslatableSlug;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that are translatable.
     *
     * @var array
     */
    protected $translatable = ['name', 'slug'];

    /**
     * Get the options for generating the slug.
     *
     * @return \Spatie\Sluggable\SlugOptions
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }
...
```

**api.php:**

```php
Route::apiResource('restaurants', RestaurantController::class)
    ->scoped(['restaurant' => 'slug']); // Alternative to getRouteKeyName(), which doesn't work either
```

Saved model in the database:
![image](https://user-images.githubusercontent.com/13716167/93491281-3446bc80-f912-11ea-95a1-38e798456439.png)

**dummy workflow:**
_Request:_ GET /api/restaurants/aaaa-bbbb
_Response:_ 404 Not found

_Request:_ GET /api/restaurants/cccc-dddd
_Response:_ 404 Not found

_Request:_ GET /api/restaurants/1
_Response:_ 404 Not found

**config/app.php**
```php
...
'locale' => 'en',
'fallback_locale' => 'en',
...
```

**Comment by thibodelanghe** [comment]
it's because the value in the database is with translation data etc => `{'en' => 'aaaa-bbbb', 'fr' => 'cccc-dddd'}`. So if you do an SQL `where` it'll not return any rows since it's not 'present'

**Comment by andriihorpenko** [comment]
Yeah, I assumed that this might be the root of the issue, but we still need a workaround for that.

**Comment by thibodelanghe** [comment]
@andriihorpenko I just edited my comment

**Comment by andriihorpenko** [comment]
Got it, that's what I actually did to solve this problem. However, I think it would be much more convenient to have a native solution in the package itself.

**Comment by thibodelanghe** [comment]
It's possible to define the resolve logic in the model itself so it's possible to maybe add it in the HasTranslatableSlug trait.

This does the trick on model level
```
    public function resolveRouteBinding($value, $field = null)
    {
        return $this->where('slug->' . app()->getLocale(), $value)->firstOrFail();
    }
```

**Comment by mehrangolestani** [comment]
not support farsi(persian)!????

**Comment by oliver-la** [comment]
@freekmurze Would it be possible to include the code from https://github.com/spatie/laravel-sluggable/issues/171#issuecomment-703868388 in the HasTranslatableSlug trait? Because model resolution does not work out of the box.

**Comment by trippo** [comment]
I think is better:
```php
public function resolveRouteBinding($value, $field = null)
    {
        if ($this->translatable && in_array($field, $this->translatable)) {
            return $this->where($field . '->' . app()->getLocale(), $value)
                ->orWhere($field . '->'. config('translatable.fallback_locale'), $value)->firstOrFail();
        } else {
            return parent::resolveRouteBinding($value, $field);
        }
    }
```
