### ISSUE TITLE
syntax error, unexpected 'SlugOptions'

### ISSUE THREAD

**Issue by jeslabbert** [spatie/laravel-sluggable#178]
Hi there,

I have been using laravel-sluggable for a while now and its a great plugin.

Unfortunately the server I am hosting on updated PHP from 7.4.1 to 7.4.11.

I have noticed that with the update it breaks laravel-sluggable. I reverted back to PHP 7.4.1 and all is fine.

Here is the error I received:
`syntax error, unexpected 'SlugOptions' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)`

I am running laravel 7. 

Here is my php -v output

`PHP 7.4.11 (cli) (built: Oct 18 2020 19:39:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
`

**Comment by freekmurze** [comment]
You're not fully on PHP 7.4: https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by izshreyansh** [comment]
Very likely you've recently installed PHP 7.4 but your nginx configuration file still points to PHP 7.3-fpm.
Updating that should fix the problem.
