### ISSUE TITLE
Disable translate or transform title !

### ISSUE THREAD

**Issue by EGYWEB-Mohamed** [spatie/laravel-sluggable#181]
Hello Thanks for this awesome package ♥
The most title is in the Arabic language so Slugable transform it into English letter
I need it in the same formate as the example

مرحباً هذا العنوان
مرحباً-هذا-العنوان

the package transform it to

مرحباً هذا العنوان
mrhba-htha-alaanoan

**Comment by freekmurze** [comment]
Feel to PR this to the package. Make sure to include tests and an updated readme.

**Comment by EGYWEB-Mohamed** [comment]
I fix it by adding usingLanguage(false) instead of 'en' by default and if I add 'ar' it's work as well

![image](https://user-images.githubusercontent.com/23424932/99309891-d6c3e300-2862-11eb-992d-efd7599590df.png)
