### ISSUE TITLE
Object of class Spatie\Sluggable\SlugOptions could not be converted to string

### ISSUE THREAD

**Issue by junitobermudez** [spatie/laravel-sluggable#183]
I updated my application to Laravel 8.x today and I am now getting the following 500 error. `Object of class Spatie\Sluggable\SlugOptions could not be converted to string` Please let me know if there was something I missed when updating to 8.x

**Comment by freekmurze** [comment]
Could you reopen this as a discussion in the Q&A category? Thanks!
