### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by olimorris** [spatie/laravel-sluggable#2]
I kept on getting a `Fatal error: Class 'App\SlugOptions' not found` when implementing this in Eloquent. Easy to fix, just `use Spatie\Sluggable\SlugOptions;`.

The readme doesn't tell me to do that. Also, there are references to `use Spatie\Sluggable\Slug;` when it should be `use Spatie\Sluggable\HasSlug;`.

That aside this is a lovely and simple slug package.

If you agree with the above, I'll happily submit a pull request.

**Comment by freekmurze** [comment]
I'm sorry if the readme was not clear on this.

I'd be very grateful for a PR that makes the readme better. :+1:
