### ISSUE TITLE
Add a list of deny slugs

### ISSUE THREAD

**Issue by Rene-Roscher** [spatie/laravel-sluggable#202]
Hello, a list of forbidden words would be very helpful.

Just add another function to the options, which is as follows SlugOptions::denyList(['storage'] : array) - so if one of the keywords is set, just randomly put a number after it.

**Comment by freekmurze** [comment]
I see this as beyond the scope of our package.

**Comment by bram-pkg** [comment]
I agree this would be a good feature to have. Sometimes URL's can include certain words that are hardcoded, such as `latest` or `current`.
