### ISSUE TITLE
Option to destroy the getSlugOptions function

### ISSUE THREAD

**Issue by jayked** [spatie/laravel-sluggable#21]
First of all thanks for the great package.
I'm using version 1.2.0 (and can't update for that matter).
I'm having the following situation : 
I am using a model called Page in a selfmade package : 
```php
<?php
	namespace MyPackage\Models;

	use Spatie\Sluggable\SlugOptions;
	use Illuminate\Database\Eloquent\Model;

	class Page extends Model
	{
               public $table = 'pages';

		// Custom fillable for the developer variable
		protected $fillable = [
			'title',
                        'slug'
		];

		/**
		 * Get the options for generating the slug.
		 */
		public function getSlugOptions() : SlugOptions
		{
			return SlugOptions::create()
				->generateSlugsFrom('title')
				->saveSlugsTo('slug');
		}
	}
```
And I want to overwrite it using my own class : 
```php
<?php
	namespace App\Models;

	use Spatie\Sluggable\SlugOptions;
	use MyPackage\Models\Page as OriginalModel;

	class Page extends OriginalModel
	{
		// Custom fillable for the developer variable
		protected $fillable = [
			'title',
                       'content'
		];
	}
```
But this new model doesn't use the `slug` column in the database (I have removed it using migrations) and so I want to disable the getSlugOptions function. Is there a solution for me?

**Comment by freekmurze** [comment]
I'm afraid it do not understand what your issue is. I don't see `rank` anywhere in the code you posted.

**Comment by jayked** [comment]
Whoops. I meant the `slug` column instead of `rank`. My bad. I've updated the issue.

**Comment by freekmurze** [comment]
I'd create a second model `UnsluggledPage` (or something with a better name). That doesn't have a `getSlugOptions` method. 

You could let `Page` extend from `UnsluggedPage` and add the `getSlugOptions` to `Page`.
