### ISSUE TITLE
Slug doesn't generate on old models

### ISSUE THREAD

**Issue by keizah7** [spatie/laravel-sluggable#211]
I have old data and using seeder to generate slugs, but it doesn't generate until column is modified.

Not working:
```
Apartment::query()
    ->where('slug', '')
    ->each(function (Apartment $apartment) {
        $apartment->room_type_name = $apartment->room_type_name;
        $apartment->save();
    });
```

Works:
```
$apartments = Apartment::query()
    ->whereNull('slug')
    ->get();

$apartments->each(function (Apartment $apartment) {
    $apartment->timestamps = false;
    $apartment->room_type_name = $apartment->room_type_name . ' ';
    $apartment->save();
});

$apartments->each(function (Apartment $apartment) {
    $apartment->timestamps = false;
    $apartment->room_type_name = Str::substr($apartment->room_type_name, 0, -1);
    $apartment->save();
});
```

Settings:
```
public function getSlugOptions(): SlugOptions
{
    return SlugOptions::create()
        ->generateSlugsFrom('room_type_name')
        ->saveSlugsTo('slug');
}
```

**Comment by Jhnbrn90** [comment]
Dear @keizah7 

The `laravel-sluggable` library hooks in on the `static::updating` lifecycle event of the specific Model. 
The `updating` hook is however only triggered when a change in attributes is detected. In your described case, there are no updated values and the `updating` hook is not called and therefore no slugs are generated or updated. 

In the `laravel-sluggable` package I came across the `generateSlug()` method on the `HasSlug` trait which you can nicely put to use in your example: 

```
    $appartments = Appartment::query()
        ->where('slug', '')
        ->each(function (Appartment $appartment) {
            $appartment->generateSlug();
            $appartment->save();
        });
```

This will generate a slug for all the `Appartment` models where the `slug` column is empty.

**Comment by keizah7** [comment]
@Jhnbrn90 thank you!
