### ISSUE TITLE
Overloading the slug generator

### ISSUE THREAD

**Issue by blackfyre** [spatie/laravel-sluggable#22]
Hi!

There's a problem with slugifying non-Germanic languages (Hungarian, Turkish, ...) that use the `ö`, `ü` characters. The components that are imported from Stringy don't make a distinction for these cases.

One solution would be an ability to change the slug generation method with `str_slug()` as a fallback.

**Comment by blackfyre** [comment]
I've found a way to overload the `str_slug()`, so no modifications are needed 😄

**Comment by freekmurze** [comment]
Hi, 

great you found a way to solve this. Could you share your solution for future users who might have the same question?

**Comment by blackfyre** [comment]
Sure, I was just polishing a blog entry for this :smile: 

For everyone who has similar issues: https://blackfyre.ninja/blog/fixing-slug-generation-problems

**Comment by khanof89** [comment]
@blackfyre your blog doesn't works
