### ISSUE TITLE
Any lightweight alternative for php5

### ISSUE THREAD

**Issue by netwrkx** [spatie/laravel-sluggable#28]
This package work well on my dev server(php7) but my production server running on php5 and its flagging some errors

```
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->slugsShouldBeNoLongerThan(70);
    }
```
Any lightweight alternatives for php5?

**Comment by sebastiandedeyne** [comment]
Sorry, we only support php 7 for this package. If you need php 5 support, you're going to have to fork this repository.
