### ISSUE TITLE
What if user want to use '_' instead of '-' for space

### ISSUE THREAD

**Issue by mtilokani** [spatie/laravel-sluggable#29]
What if user want to use '_' instead of '-' for space ?

**Comment by sebastiandedeyne** [comment]
Currently not possible I'm afraid. I'd accept a PR that adds a `separator` property and a `withSeparator(string $separator)` method to `SlugOptions`.

**Comment by mtilokani** [comment]
Great thanks.

Even I will also try to add/contribute this feature.

**Comment by freekmurze** [comment]
`usingSeparator()` has been added in `v1.5.0`

**Comment by mtilokani** [comment]
@freekmurze - thanks :+1:
