### ISSUE TITLE
Throw Error: BadMethodCallException

### ISSUE THREAD

**Issue by assoft** [spatie/laravel-sluggable#31]
- Laravel Version: Laravel Framework 5.4.18
- Php Version: PHP 7.0.15
- DB: sqlite

Model => News.php
```
use Spatie\Tags\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasSlug;

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }
}
```

```
php artisan db:seed --class=NewsTableSeeder
```

**Throw error:**
```BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::getTranslatedLocales()'```

Where's the error?

**Comment by freekmurze** [comment]
`getTranslatedLocales` is not a function from this package. The exception trace should help you find out where this exception is being thrown.

**Comment by assoft** [comment]
This error stems from the first row: 

```use Spatie\Tags\HasSlug;```

change this

```use Spatie\Sluggable\HasSlug;```

Thank you... 

I apologize for the unnecessary topics.

**Comment by freekmurze** [comment]
Np, glad you found it!
