### ISSUE TITLE
Model with parent/s creating hierarchy

### ISSUE THREAD

**Issue by dror3go** [spatie/laravel-sluggable#33]
Hi,

I'm developing a site that has a `Page` model, with a `page_id` column to create sort of an hierarchy for the pages. The result should be URLs with slashes concatenation of the slugs, so if for example page with id 1 has the slug _hello_ will be accessible through mydomain.com/hello and if it has a "child page" which is a page with `page_id` of 1 and a slug of _world_ - it will be accessible through mydomain.com/hello/world

I'm interested in using this package to create the slugs, but would appreciate to get your input for how to implement such a thing:

- Would you set a pretty long slug for the model, and alter the default slug logic to fetch all parents slugs, and concatenate them with slashes?
- Would you keep the default slug logic, and create a "sophisticated" function to fetch a page by a given "full slug"?
- Would you set two slug columns, on normal and a second which is the full-slug?
- Maybe something else?

Much appreciated, and thanks for the package!

**Comment by freekmurze** [comment]
I got no real preference, depends on the project. Do what you feels is best.
