### ISSUE TITLE
Supporting UTF8

### ISSUE THREAD

**Issue by mohamedsabil83** [spatie/laravel-sluggable#34]
How can I accept UTF-8 characters like Arabic in sluggable for example:

أحمد محمد need to be 'أحمد-محمد' instead of 'ahmd-mhmd'?

**Comment by freekmurze** [comment]
Currently `str_slug` is used to generate slugs. That function is hard coded. I'd accept a fully tested, non-breaking PR that allows that slug function to be changed via a new setting in the config file.

**Comment by ctf0** [comment]
@mohamedsabil83 here is a solution for the slug in arabic issue
```php
$url = trim($string);
$url = strtolower($url);
$url = preg_replace('|[^a-z-A-Z\p{Arabic}0-9 _]|iu', '', $url);
$url = preg_replace('/\s+/', ' ', $url);
$url = str_replace(' ', $separator, $url);

return $url;
```

this works for both arabic & english

**Comment by bobbybouwmann** [comment]
The `str_slug` method has support for a language flag, did you try that one?
```
`str_slug($string, $separator, $language)`
```

**Comment by freekmurze** [comment]
Did not know that language flag @bobbybouwmann 
Thanks for mentioning that.

**Comment by ctf0** [comment]
@bobbybouwmann https://laravel.com/api/5.4/Illuminate/Support/Str.html#method_slug , cant find any lang flag 👀

**Comment by Luceos** [comment]
Allow me to link this to an extensive discussion on the Flarum forum repository about Slug transliteration,

https://github.com/flarum/core/issues/194

**Comment by rathesDot** [comment]
@ctf0 5.4 does not have this flag, but checkout Illuminate/Support/helpers.php at master branch: https://github.com/laravel/framework/blob/master/src/Illuminate/Support/helpers.php

**Comment by ctf0** [comment]
@rathesDot ahaaa thats why then, its in a next release not the current v5.4

**Comment by bobbybouwmann** [comment]
Aah sorry, I was working on dev-master the other day and found that flag! 

@freekmurze Let's wait for 5.5 or do you want a dirty fix for this for now?

**Comment by freekmurze** [comment]
Nah, let's wait for 5.5

**Comment by mohamedsabil83** [comment]
Thanks @ctf0 for your suggestion. @freekmurze I'm using [eloquent-sluggable](cviebrock/eloquent-sluggable) and updating the configuration from [morilog/eluquent-sluggable-persian](https://github.com/morilog/eluquent-sluggable-persian) to enable real string slugging instead of changing it to English slugging.
As you said, @freekmurze, 

> Nah, let's wait for 5.5

Thank you all.

**Comment by the94air** [comment]
Laravel 5.5 has been relased. Any news about this issue?

**Comment by freekmurze** [comment]
I'd accept a fully tested, non-breaking PR that adds the ability to specify a language in the SlugOptions. The chosen language should be passed to the `str_slug` function. Extra points if the PR also updates the docs with an example on how to use the new functionality.

**Comment by PendoNL** [comment]
Challenge accepted, first time ever, so be gentle!

https://github.com/spatie/laravel-sluggable/pull/45

**Comment by freekmurze** [comment]
Thanks @PendoNL 

We'll handle this further in #45

**Comment by AO-IO** [comment]
if anyone still has Problems in using Arabic chars in slug.

Solution 💯 👍 :

by using https://github.com/cocur/slugify.

go to `HasSlug` Trait in `vendor/spatie/laravel-sluggable`

at the top use `use Cocur\Slugify\Slugify;`

override the method `generateNonUniqueSlug()`


```PHP

protected function generateNonUniqueSlug(): string
    {
        $slugField = $this->slugOptions->slugField;
        if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
            return $this->$slugField;
        }

        $slugify = new Slugify(['rulesets' => ['default', 'arabic']]); // your language 

        return $slugify->slugify($this->getSlugSourceString(), $this->slugOptions->slugSeparator);
    }


```

**Comment by jahanur96** [comment]
function slugify($string)
    {
        return mb_strtolower(preg_replace('/[ ,.@#$#%^&*?~()_\/\'=]+/', '-', trim($string)), 'UTF-8');
    }
