### ISSUE TITLE
Overwrite a slug

### ISSUE THREAD

**Issue by simondepelchin** [spatie/laravel-sluggable#4]
Hi @freekmurze, I was wondering how I could overwrite a generated slug from my form?

One option I have in mind is creating a `slug_overwrite` field and overwrite the `getSlugAttribute()` to return either `slug_overwrite` or `slug`.

Is that a good idea ?

**Comment by freekmurze** [comment]
Overwriting a generated slug could work without introducing an extra field like `slug_overwrite`.

To the package could check, before updating a record, if the currently generated slug matches the slug that would be generated by the current slug source. If it is not, then a custom slug has been set. and so the package should not update that custom slug.

I think this would be usefull and I'd accept a PR that adds this to the package.

**Comment by freekmurze** [comment]
Fixed by your PR. Changes are present in newly tagged version 1.1.0
