### ISSUE TITLE
Adding package to existing project

### ISSUE THREAD

**Issue by amosmos** [spatie/laravel-sluggable#41]
Hey, is there a way to populate slugs to all existing models? I added the package after I had many items in my DB.

Thanks!

**Comment by sebastiandedeyne** [comment]
We don't ship anything specific to do this, but you can achieve is with a relatively small script. You could place it in an artisan command for example.

```
MyModel::all()->each(function ($myModel) {
    $myModel->generateSlug();
    $myModel->save();
});
```

Or if you're on 5.4 and feeling fancy... (I think at least haven't tested this 😄)

```
MyModel::all()->each->generateSlug()->each->save();
```

**Comment by amosmos** [comment]
Thanks - will try it out!

Do you think this is something you might add to the package one day? I assume it will make it easier for many developers to use it in existing projects...
