### ISSUE TITLE
Testing results in mkdir(): File exists

### ISSUE THREAD

**Issue by wgmv** [spatie/laravel-sluggable#47]
I was testing this package the other day and received this result with phpunit (only one test passes the others fail, probably because the sqlite db already exists:

```
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1
Configuration: laravel-sluggable/phpunit.xml.dist

.EEEEEEEEEEEEEEEEEEEEEE                                           23 / 23 (100%)

Time: 975 ms, Memory: 12.00MB

There were 22 errors:

1) Spatie\Sluggable\Test\Integration\HasSlugTest::it_can_handle_null_values_when_creating_slugs
ErrorException: mkdir(): File exists
```

Am I doing it wrong? Thanks for any advice.

**Comment by markwalet** [comment]
The documentation says that you have to run `composer test`. Does that work?

**Comment by wgmv** [comment]
same result. The test script also just calls phpunit?

`"scripts": {
        "test": "phpunit"
    }`

**Comment by sebastiandedeyne** [comment]
That's odd, seems to work here and on CI...

If you're still having issues here, feel free to reopen or discuss.

**Comment by belzaaron** [comment]
+1 for this long-dead issue. Not sure the cause at the moment. Happening on latest tag https://github.com/spatie/laravel-sluggable/releases/tag/2.2.0.
