### ISSUE TITLE
optional parameter

### ISSUE THREAD

**Issue by Fatih90** [spatie/laravel-sluggable#49]
Hi is it possible to make a slug from
title: `Mad Max: Fury Road`
to
slug: `341-mad-max-fury-road` where the '341' is the id from table ?

i actualy don't need this package for now but i want to use it for my future projects becaue it has the name Spatie before it ;)

**Comment by freekmurze** [comment]
You can override this function in your model to customize the slug.

https://github.com/spatie/laravel-sluggable/blob/cc9c261b108d98aa00493585f6bd20b639d0a6f2/src/HasSlug.php#L90-L99
