### ISSUE TITLE
hasCustomSlugBeenUsed on update error

### ISSUE THREAD

**Issue by wolflingorg** [spatie/laravel-sluggable#53]
Hi. I'm using "laravel-sluggable" 2.1.0

Could you help me please to figure out of what am I doing wrong?

I have a model SomeModel with *title* and *slug* fields

```php
public function getSlugOptions() : SlugOptions
{
    return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
}
```
When I create a model with an empty *slug* "laravel-sluggable" takes the *title* and create a *slug* automatically.

When I try to update an existed model with an empty *slug* (for example when I need to change a *title* and clear the *slug* field so that system can generate it automatically)

```php
$someModel->update([
    'titile' => 'some new title',
    'slug' => ''
]);
```
I have an exception:

`"Type error: Return value of SomeModel::generateNonUniqueSlug() must be of the type string, object returned"`

Wouldn't it be better to change a bit *hasCustomSlugBeenUsed* method and append an additional check like `!is_null($this->$slugField)`:

```php
/**
 * Determine if a custom slug has been saved.
 */
protected function hasCustomSlugBeenUsed(): bool
{
	$slugField = $this->slugOptions->slugField;

	return !is_null($this->$slugField) && $this->getOriginal($slugField) != $this->$slugField;
}
```

Or is there another solution?

Thx for a help.

**Comment by freekmurze** [comment]
I'd accept a PR with a test that improves this behaviour.
