### ISSUE TITLE
If title contains special characters, it doesn't discard those

### ISSUE THREAD

**Issue by milanchheda** [spatie/laravel-sluggable#58]
I am using this default code to generate slugs from title:

```php
/**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }
```

If my title contains characters such as, (, [, ], ), +,... those should ideally be excluded while creating slugs, but they aren't. 

Example:

Title: Blog (Using PHP, MySQL & JQuery)
Slug generated: Blog-%28Using-PHP,-MySQL-&-JQuery%29

Slug should be: Blog-Using-PHP-MySQL-JQuery

**Comment by freekmurze** [comment]
Could you PR a failing test for me to fix?

**Comment by milanchheda** [comment]
Not sure, if PR is needed. I think, I have missed something but don't know what it is..

I see on [murze.be](https://murze.be) that post titles do have '(', ':' and '!', but the respective URLs are formed correctly without this characters. I did checked the code for murze.be but couldn't figure out what / which configuration I am missing for this characters :(
