### ISSUE TITLE
spatie/laravel-sluggable 1.1.0 requires php >=7.0.0

### ISSUE THREAD

**Issue by sebestenyb** [spatie/laravel-sluggable#6]
Hi

Is it possible to lower the php requirement? Does it really need to be >=7.0.0?
It's a bit of an issue, php 7.0 is not yet available everywhere.

Cheers, Sebi

**Comment by freekmurze** [comment]
Here's [the reasoning behind requiring PHP 7](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/).
