### ISSUE TITLE
Issue when Model uses UUIDs

### ISSUE THREAD

**Issue by mkriegeskorte** [spatie/laravel-sluggable#63]
Hi there,

first of all: Thank you for your work! I really appreciate your packages and the features you provide to the community.

I implemented the sluggable package into one of my uuid-enabled models. Unfortunately there seems to be a problem at the time the package looks for uniqueness in the database.

Here are the code which I'm using at the Model:

```
class Item extends Model
{
    use Uuid, SoftDeletes, HasSlug;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }
}
```

On inserting a new record I'm receiving the following exception:
`SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type uuid: "0" (SQL: select * from "items" where "slug" = test and "id" != 0 limit 1)`

Do you have any idea how to fix this the right way?

Thanks in advance for your help and advice.

Kind regards
Martin

**Comment by TVke** [comment]
Dear @mkriegeskorte 

Which package do you use to implement the Uuid, so I can test it the correct circumstances. 

Greetings
Thomas

**Comment by mkriegeskorte** [comment]
Hi @TVke!

Formerly I was using `Ramsey\Uuid`. By upgrading to Laravel 5.6 I'm using Str::Uuid, which relies on Ramseys package.

Here's my trait I'm currently using:

```
<?php
namespace App;

use Illuminate\Support\Str;

/**
 * Class Uuid.
 *
 * Generates new Uuid primary key in case no PK provided.
 */
trait Uuid
{
    /**
     * The "booting" method of the model.
     */
    protected static function boot()
    {
        parent::boot();
        /**
         * Attach to the 'creating' Model Event to provide a UUID
         * for the `id` field (provided by $model->getKeyName()).
         */
        static::creating(function ($model) {
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = $model->generateNewUuid();
            }
            return true;
        });
    }
    
    /**
     * Get a new version 4 (random) UUID.
     *
     * @return \Ramsey\Uuid\Uuid
     */
    public function generateNewUuid()
    {
        return Str::orderedUuid();
    }
}
```

Greetings
Martin

**Comment by TVke** [comment]
Hey @mkriegeskorte 

I made a PR could you test if it works for your setup?

Greetings
Thomas

**Comment by mkriegeskorte** [comment]
Hey @TVke,

that does work like a charm! Thank your for the support.

Kind regards
Martin

**Comment by TVke** [comment]
@mkriegeskorte You are very welcome

**Comment by freekmurze** [comment]
This is fixed in `2.1.3`.

**Comment by denniskoster** [comment]
Hi, I am using a PostgreSQL database, which automatically generates uuid's. 

Unfortunately I can not simply set the `$incrementing` property of my models to `false`, because Laravel will no longer return the key of a generated model anymore. See https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Model.php#L856.

Do you see a way around this, other than overruling the `otherRecordExistsWithSlug` method, so that it no longer looks for a `0` key?

**Comment by denniskoster** [comment]
I have created a pull request to fix this issue: https://github.com/spatie/laravel-sluggable/pull/173
