### ISSUE TITLE
Incompatibility with php7.2

### ISSUE THREAD

**Issue by mwakaambrose** [spatie/laravel-sluggable#66]
I pull in the latest version.
Am using laravel 5.4 with php7.2 here is the error I get.
![screen shot 2018-03-01 at 14 04 56](https://user-images.githubusercontent.com/8328295/36841577-cd4e2d2e-1d59-11e8-879e-f0eb5c67fffb.png)

**Comment by freekmurze** [comment]
The tests [seem to indicate](https://travis-ci.org/spatie/laravel-sluggable/jobs/345630700) that the package is working correctly on PHP7.2 

Could PR a failing test?

**Comment by mwakaambrose** [comment]
Seems like it's a problem with my code. I tried reproducing it, test kept passing. Sorry.

![screen shot 2018-03-01 at 16 23 10](https://user-images.githubusercontent.com/8328295/36846754-f2218106-1d6c-11e8-845e-457d9441873b.png)

**Comment by mwakaambrose** [comment]
@freekmurze It seems to be failing at this point when an seeding the model. Any idea?
```php
    /**
     * This function will throw an exception when any of the options is missing or invalid.
     */
    protected function guardAgainstInvalidSlugOptions()
    {
        if (! count($this->slugOptions->generateSlugFrom)) {
            throw InvalidOption::missingFromField();
        }
        ...
```
