### ISSUE TITLE
Efficiency could be improved

### ISSUE THREAD

**Issue by sander3** [spatie/laravel-sluggable#7]
Have you ever thought of something like this:

```
    public static function generateUniqueSlug($name)
    {
        $slug  = Str::slug($name);
        $count = self::withTrashed()->whereRaw("slug REGEXP '^{$slug}(-[0-9]*)?$'")->count();

        if ($count > 0) {
            return $slug . '-' . ($count + 1);
        }

        return $slug;
    }
```

**Comment by freekmurze** [comment]
Currently we don't experience any performance issues in our projects. Our sites generally have pages with unique names / slugs so we don't have to loop much to get a unique slug.

I would however accept a PR that makes the current loop more efficient.
