### ISSUE TITLE
maximumLength applies to source and not slug

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-sluggable#71]
The `maximumLength` is used to shorten the source string and not to limit the slug length.
But related to the readme it should limit the generated slug:
> You can also put a maximum size limit on the created slug:

This will lead to problems if it's used to limit slug length cause DB column is limited or to ensure that the final URL isn't longer.

**Comment by freekmurze** [comment]
Added `The slug may be slightly longer than the value specified, due to the suffix which is added to make it unique.` to the readme.
