### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-sluggable#75]
I have seen other issues for UTF-8 but since you're using `str_slug` and they have made a terrible choice to convert all characters to ASCII, the issue is not resolved yet.

Since the whole purpose of slugs is SEO, we must be able to use UTF-8 characters. I suggest we stop using `str_slug`.

**Comment by mokhosh** [comment]
And the worst thing is the package is not even using `str_slug` so you can override it with a hack, it's using `Str::slug`.

**Comment by sebastiandedeyne** [comment]
I don't think we want to maintain a custom slug generator function. If this is easily done, feel free to send a well tested PR with the changes.

In the mean time, if this is an issue for anyone, you can override the `HasSlug` trait's `generateNonUniqueSlug` method.
