### ISSUE TITLE
slug unique by another field (so "versions" of an entry may share the slug)

### ISSUE THREAD

**Issue by jayenne** [spatie/laravel-sluggable#77]
I have a need to create a simple versioning system that would require a unique slug but obviously one which is shared acrooss alll versions of the same page/article. would it be possible/desireable to have a method that allows the 'unique' be maintained true for all entries with a given field/value?
e.g: 'slug' => 'foo' where 'page_id' => '100' 

*given that all entries hava a slug field and a page_id field and that the page_id field is common to all versions of a given page.

thoughts?

**Comment by freekmurze** [comment]
Thanks for your proposal, but I think most users don't need this functionality.  I'd like to keep the package as simple as possible.

**Comment by hakimihamdan88** [comment]
need this
