### ISSUE TITLE
Implicit route model binding incompatible with laravel-binary-uuid package?

### ISSUE THREAD

**Issue by hakimzulkufli** [spatie/laravel-sluggable#78]
With Laravel 5.6, I tried using implicit Route model binding with this package but it doesn't work. I am also using the Binary UUID package made by your company. Through the debugbar package, I found that Laravel was looking for the slug from the `uuid` column instead of the `slug` column even though I have defined it using `getRouteKeyName()`.

Debugbar also revealed that the query was made through the `HasBinaryUuid` trait. There's a `getRouteKeyName()` defined inside `HasBinaryUuid` trait. I think that's the one that overriden the `getRouteKeyName()` defined in my own model file.

How do I make sure that my own `getRouteKeyName()` function takes precedence over anything else?

**Comment by hakimzulkufli** [comment]
After testing, I commented out `getRouteKeyName()` and `resolveRouteBinding()` from `HasBinaryUuid` and now the route model binding works.

**Comment by freekmurze** [comment]
It's normal behaviour for PHP to pick the class implementation over a trait implementation. Are you sure you defined `getRouteKeyName` right? Try to add some `dd` in both implementations to know which one is loaded.

**Comment by hakimzulkufli** [comment]
Just to be extra safe, I even tried copy pasting the function from both Laravel's documentation and the one from `HasBinaryUuid`. I'm not sure how to use `dd` in a way that you were suggesting but according to the laravel-debugbar package, the query was `select * from `users` where `users`.`uuid` in ('administrator') limit 1` and was made through `\vendor\spatie\laravel-binary-uuid\src\HasBinaryUuid.php:207`. This is when I left the `HasBinaryUuid` file as is.

After commenting both `getRouteKeyName` and `resolveRouteBinding` from `HasBinaryUuid`, the query made was `select * from `users` where `slug` = 'administrator' limit 1` through `\vendor\laravel\framework\src\Illuminate\Routing\ImplicitRouteBinding.php`.

I am using php 7.1.20, by the way.
