### ISSUE TITLE
Assign slug based on request value

### ISSUE THREAD

**Issue by sergeynilov** [spatie/laravel-sluggable#79]
Hello!

In my Laravel 5.6 application using         "spatie/laravel-sluggable": "^2.1" plugin
I need to fill slug field for a table with additive translation table, so for a table
artists name field is located in artist_translations table,

If there is a way to base new created slug based on value in request? With all fields in 1 table I did priorly as :

```

class Artist extends MyAppModel
{
    use HasSlug;

    protected $table = 'artists';
    protected $primaryKey = 'id';

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
                          ->generateSlugsFrom('name')
                          ->saveSlugsTo('slug');
    }

```

How ?

Thank you!

**Comment by freekmurze** [comment]
The package cannot do this. Handle that scenario in your own app.
