### ISSUE TITLE
Validate the slug before it is saved?

### ISSUE THREAD

**Issue by prjctnxt** [spatie/laravel-sluggable#83]
I'm sorry, I'm quite confused. I have run into a problem with a title that will pass all my form request rules but then return an empty slug via sluggable (a title consisting purely of emojis).

Ideally all requests returning an empty slug would throw an error but if that's not possible I would like to validate the result.

Is this simple to do? I am using Sluggable by including the trait in the model.

**Comment by freekmurze** [comment]
The package contains no functionality to do this. However, it's very easy to create a [custom rule](https://laravel.com/docs/master/validation#custom-validation-rules) yourself. In that rule you should validate if the value given returns a non empty string when passing the value to `str_slug`.
