### ISSUE TITLE
Error when updating and having slug empty

### ISSUE THREAD

**Issue by josegus** [spatie/laravel-sluggable#84]
![image](https://user-images.githubusercontent.com/13947849/49896668-73390b80-fe2a-11e8-98ca-2a645b0d6542.png)

I'm getting this error when I update my model and set slug to null.

My slugOptions is this:

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('nombre')
            ->saveSlugsTo('slug');
    }

**Comment by freekmurze** [comment]
Feel free to PR a fix and a test that proves that the fix works for this 👍

**Comment by VincentKos** [comment]
What is the expected behavior here @freekmurze ? 

The slug row should have `-1` as a value or he should use the `nombre` field to create the slug even if the slug field is given but empty?

**Comment by freekmurze** [comment]
it should use the nombre field to create the slug
