### ISSUE TITLE
Compatibility with spatie/laravel-translatable

### ISSUE THREAD

**Issue by lidoma** [spatie/laravel-sluggable#85]
Hi
Is this package compatible with `spatie/laravel-translatable` package? I try to implement this but it does not work.

**Comment by freekmurze** [comment]
The packages are indeed incompatible. I'm afraid there's no easy way to use them together. 

In our projects we sometimes used this approach to generate slugs (without using the package) for translatable models: https://github.com/spatie/blender/blob/master/app/Models/Traits/HasSlug.php

**Comment by okaufmann** [comment]
How about using data_get to retrieve field value (using here https://github.com/spatie/laravel-sluggable/blob/master/src/HasSlug.php#L123)?

```php
$slugSourceString = collect($this->slugOptions->generateSlugFrom)
            ->map(function (string $fieldName) : string {
                return data_get($this, $fieldName) ?? '';
            })
            ->implode($this->slugOptions->slugSeparator);
```

Then we could define the following SlugOptions

```php
 /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name.de')
            ->usingLanguage('de')
            ->saveSlugsTo('slug');
    }

```

This will not break any existing functionality but will allow to still use this package and its cool features?

**Comment by freekmurze** [comment]
@okaufmann that's a really nice solution, thanks!

**Comment by CreativeBulma** [comment]
Hi,

just wanted to share the way we handle the cohabitation between Sluggable and Translatable:
We have extended the default Illuminate Model into a BaseModel with the following method in it:

```php
public function resolveRouteBinding($value)
{
        $key = $this->getRouteKeyName();

        // We don't use $this->isTranslatableAttribute($key) because in case HasSlug Trait has not been added to the model
        if ($this->translatable && in_array($key, $this->translatable)) {
            return $this->where($key . '->' . app()->getLocale(), $value)->first();
        } else {
            return $this->where($key, $value)->first();
        }
}
```
