### ISSUE TITLE
Use in seeds

### ISSUE THREAD

**Issue by jarod51** [spatie/laravel-sluggable#9]
Hi

I would like to know how to use this extension in a seeder ? (I followed the readme but no slug are generated, i think the seeders does not use the models )

Thank you :)

**Comment by sebastiandedeyne** [comment]
It depends how you're writing your seeds!

Could you post a snippet?

**Comment by jarod51** [comment]
@sebastiandedeyne here it is

https://gist.github.com/jarod51/80f41fc7d6cc3c784c232a394f9c0cc1

What i want is to generate slug from the name field

**Comment by sebastiandedeyne** [comment]
The slugs are generated when certain Eloquent events are fired, and creating records with `DB` does a plain `insert` to the database. If you want the slugs to be generated, you'll need to save them through a model.

```php
collect($brands)->each(function ($brand) { Brand::create($brand); });
```

**Comment by jarod51** [comment]
that's what i thought? I'm trying it right now

**Comment by jarod51** [comment]
Ok, it seems to work ! Thank you very much
