### ISSUE TITLE
String to lowercase 

### ISSUE THREAD

**Issue by hetais** [spatie/laravel-sluggable#92]

**Comment by hetais** [comment]
I want to just add a separator between 2 space. but this trait converts it to lower case. For example 
if I have entered "Nanomed 2019" then its convert it in "nanomed-2019" but I need like this "Nanomed-2019" as I have entered

**Comment by freekmurze** [comment]
You can override this method in your class and do the necessary modifications in that method.
https://github.com/spatie/laravel-sluggable/blob/77b67b701ec0cbf9d5ec7f91da25f69db119b2a5/src/HasSlug.php#L70-L79
