### ISSUE TITLE
Concat String

### ISSUE THREAD

**Issue by joaowall** [spatie/laravel-sluggable#94]
How do I concatenate a string between 2 fields to generate the slug?

Example:

When using SlugOptions::create()->generateSlugsFrom(['title','city']) is generated the slug:  hotels-orlando

But I would like to generate the slug: hotels-in-orlando

**Comment by staticwave** [comment]
@joaowall Could you set usingSeparator() like below?

```
public function getSlugOptions() : SlugOptions
{
    return SlugOptions::create()
        ->generateSlugsFrom(['title','city'])
        ->saveSlugsTo('slug')
        ->usingSeparator('-in-');
}
```

**Comment by JoshuaDoshua** [comment]
@staticwave 
For cities with 2 names it would generate `-in-` in between each space as well though no?
```
$model->name = "New York";
$model->slug = "hotels-in-new-in-york";
````

@joaowall 
Without knowing your app structure, I think a simpler solution to achieve some pretty URL structures might be to handle it in your routes, for example:
```
http://laravel.app/.../hotels/new-york
// or
http://laravel.app/../hotels-in/new-york
// or even
http://laravel.app/../hotels/in/new-york
```
